[default]
account = "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
user = "{{ env_var('SF_USERNAME') }}"
password = "{{ env_var('SF_PSWD') }}"
role = "{{ env_var('SF_ROLE') }}"
warehouse = "{{ env_var('SF_WAREHOUSE') }}"
database = "{{ env_var('SF_DATABASE') }}"
