- name: Run schemachange
  env:
    SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SF_USERNAME: ${{ secrets.SF_USERNAME }}
    SF_PSWD: ${{ secrets.SF_PSWD }}
    SF_ROLE: ${{ secrets.SF_ROLE }}
    SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
    SF_DATABASE: ${{ secrets.SF_DATABASE }}
  run: |
    pip install --upgrade --no-cache-dir schemachange
    chmod 600 $GITHUB_WORKSPACE/connections.toml
    schemachange -f deploy \
      --connections-file-path $GITHUB_WORKSPACE/connections.toml \
      --connection-name default \
      -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
      --create-change-history-table
